### ISSUE TITLE
gcc requires different link order on Linux

### ISSUE THREAD

**Issue by rtfb** [justinas/go-build-modes#1]
For a reference, needed to change the link order to get it working on my box:

``` diff
$ git df
diff --git a/Makefile b/Makefile
index 42494a7..35bebf5 100644
--- a/Makefile
+++ b/Makefile
@@ -6,10 +6,10 @@ libmath.a: math.go
        go build -buildmode=c-archive -o libmath.a math.go

 dynamic: libmath.so
-       cc -L. -lmath -o math math.c
+       gcc math.c -L. -lmath -o math

 static: libmath.a
-       cc libmath.a math.c -o math
+       gcc math.c libmath.a -lpthread -o math
```

Also, run with `LD_LIBRARY_PATH=. ./math`

**Comment by justinas** [comment]
I vaguely remember gcc being weird about the order of libraries, but why is LD_LIBRARY_PATH needed, doesn't `-L.` solve this at compile time?

**Comment by rtfb** [comment]
`-L.` is fine, but it's for linker; `LD_LIBRARY_PATH` is needed for runtime: Linux doesn't try to look up shared libraries in cwd.

**Comment by justinas** [comment]
I guess that makes sense. Is there a reason why `-lpthread` is only required in the static mode?

**Comment by rtfb** [comment]
Ah, good question, I promptly forgot linker asked to add it :-). My guess is that `go build` adds it when it builds the .so, but it can't add it for .a. But this is a wild guess.

**Comment by justinas** [comment]
Please reopen if ebb1070 doesn't solve this. Still have to document `LD_LIBRARY_PATH` somewhere.

**Comment by rtfb** [comment]
Can't reopen :-(
It almost did. The only thing missing is actually changing the `.dylib` to `.so` based on platform. Not sure if it's worth the effort...
